# Generated by Django 3.0 on 2023-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('model_year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('electric_vehicle_type', models.CharField(max_length=100)),
                ('cafv_eligibility', models.CharField(max_length=100)),
                ('electric_range', models.IntegerField()),
                ('base_msrp', models.IntegerField()),
                ('legislative_district', models.IntegerField()),
                ('dol_vehicle_id', models.IntegerField()),
                ('vehicle_location', models.CharField(max_length=100)),
                ('electric_utility', models.CharField(max_length=100)),
                ('census_tract', models.BigIntegerField()),
            ],
        ),
    ]
