# Generated by Django 4.2 on 2023-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricvehicle',
            name='base_msrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='cafv_eligibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='dol_vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='electric_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='electric_utility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='electric_vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='legislative_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='vehicle_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
