# Generated by Django 4.2 on 2023-04-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_vehicles', '0002_alter_electricvehicle_base_msrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricvehicle',
            name='cafv_eligibility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='county',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='electric_utility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='electric_vehicle_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='make',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='vehicle_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
